# Generated by Django 4.2.4 on 2023-08-20 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_alter_review_rating_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.watch', verbose_name='Часы'),
        ),
    ]
