# Generated by Django 4.2.4 on 2023-08-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_alter_review_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating_design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating_functionality',
            new_name='functionality',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating_quality',
            new_name='quality',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating_value',
            new_name='value',
        ),
    ]
